version: "3.7"
services:  
  db: 
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: bookshelf
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  web:
    image: bookshelf/server:v3
    depends_on: 
      - db
    ports: 
      - "3000:3000"